makerdao/spells-mainnet

archive/2020-11-06-DssSpell.sol, archive/2020-11-06-DssSpell.t.sol, compare-bytecode.sh, estimate-deploy-gas.sh, get-created-timestamp.sh, src/DssSpell.sol, src/DssSpell.t.sol
=> SC-7188 2020-11-06 Weekly Executive

archive/2020-11-13-DssSpell.sol, archive/2020-11-13-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
* Adds FLIP_FAB to changelog
* Adds GUSD
https://app.clubhouse.io/maker/story/7270/2020-11-13-executive
=> SC-7270 11/13/2020 Exec GUSD-A

.github/PULL_REQUEST_TEMPLATE.md, archive/2020-11-23-DssSpell.sol, archive/2020-11-23-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
https://app.clubhouse.io/maker/story/7272/2020-11-23-executive
```
➜  spells-mainnet git:(master) ✗ seth keccak -- "$(wget https://raw.githubusercontent.com/makerdao/community/a7c8ddb3f8d8ea71cb123b9aa45d9d7eaed8d6f0/governance/votes/Executive%20vote%20-%20November%2023%2C%202020.md -q -O - 2>/dev/null)"
0x3567e2282249022428233fe24a48a25ebc34468f2183869109f2bd590f48ef28
➜  spells-mainnet git:(master) ✗ seth keccak -- "$(wget https://raw.githubusercontent.com/makerdao/mips/5f81894b407c26373391fe6c18803eb832944d3a/MIP24/mip24.md -q -O - 2>/dev/null)"
0x6d39f78a3343fb030da792962abdd12ca1b0c9384b92f496e8a070e97cf3c1c6
➜  spells-mainnet git:(master) ✗ seth keccak -- "$(wget https://raw.githubusercontent.com/makerdao/mips/bda3f65b83668f2025e69be7897a48cb23af0bd9/MIP25/mip25.md -q -O - …
```
=> feat: 2020-11-23 Add MIPs to Monthly Exec (SC-7272)

archive/2020-11-27-DssSpell.sol, archive/2020-11-27-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
=> SC-7621 2020-11-27 weekly executive

.travis.yml, compare-bytecode.sh, shell.nix, src/DssSpell.t.sol, travis-ci.sh
=> feat: Add Bytecode Check to CI (SC-7624)

archive/2020-12-11-DssSpell.sol, archive/2020-12-11-DssSpell.t.sol, check-oracle-feed.sh, src/DssSpell.sol, src/DssSpell.t.sol, src/test/addresses_mainnet.sol
- Clubhouse ticket: [7722](https://app.clubhouse.io/maker/story/7722/2020-12-11-mainnet-executive)
- Adds [MIP27](https://forum.makerdao.com/t/mip27-debt-ceiling-instant-access-module/4625)` (`DC-IAM` or `MCD_IAM_AUTO_LINE`)
- Adds [UNI](https://forum.makerdao.com/t/uni-erc20-token-smart-contract-domain-community-assessment/5347) with [risk parameters](https://forum.makerdao.com/t/uni-collateral-onboarding-risk-evaluation/5348)
- Adds [renBTC](https://forum.makerdao.com/t/renbtc-erc20-token-smart-contract-technical-assessment/5341) with [risk parameters](https://forum.makerdao.com/t/renbtc-collateral-onboarding-risk-evaluation/5095)
- [Oracle Whitelist YFI on YFI-USD OSM Oracle](https://vote.makerdao.com/polling/Qmbutya7#vote-breakdown)
- [YFI-A Debt Ceiling 20 million DAI to 30 million …
=> feat: 2020-12-11 DC-IAM, UNI, renBTC (SC-7722)

src/DssSpell.sol, src/DssSpell.t.sol, src/test/addresses_mainnet.sol
=> WIP AAVE testing

src/DssSpell.sol, src/DssSpell.t.sol, src/test/addresses_mainnet.sol
=> WIP Aave Onboarding

src/DssSpell.t.sol
Re-enables tests and short circuits the officeHours tests when officehours is disabled.
=> Short-circuit tests when officeHours disabled

.github/PULL_REQUEST_TEMPLATE.md, .gitmodules, Makefile, archive/2021-01-15-DssSpell.sol, archive/2021-01-15-DssSpell.t.sol, archive/2021-01-15-SpellFab.sol, src/DssSpell.sol, src/DssSpell.t.sol, src/SpellFab.sol
=> SC-8258 Weekly Exec - January 15, 2021

Makefile, archive/2021-01-18-DssSpell.sol, archive/2021-01-18-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
=> feat: raise ETH-A/WBTC-A Debt Ceilings

Makefile, archive/2021-01-25-DssSpell.sol, archive/2021-01-25-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
MIPs Executive for Monday Jan 25th, 2021
=> MIPs executive Jan 25th, 2021

Makefile, archive/2021-01-29-DssSpell.sol, archive/2021-01-29-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol, test-dssspell.sh
=> SC-8758: Weekly Exec January 29, 2021

src/DssSpell.t.sol
Cat_Box Range Check Test
COB Team Name or Author(s): @naszam
=> SC-7511 Cat_Box Range Check Test

archive/2021-03-12-DssSpell.sol, archive/2021-03-12-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol, src/test/addresses_mainnet.sol
https://app.clubhouse.io/scdomaincommunityteam/story/9949/friday-12th-executive
=> SC-9949: March 12th, 2021 Weekly Exec

Makefile, archive/2021-03-19-DssSpell.sol, archive/2021-03-19-DssSpell.t.sol, shell.nix, src/DssSpell.sol, src/DssSpell.t.sol, src/test/addresses_mainnet.sol, src/test/rates.sol, test-dssspell.sh
https://app.clubhouse.io/scdomaincommunityteam/story/10175/friday-19th-executive
=> SC-10175: March 19th, 2021 Weekly Exec

.github/PULL_REQUEST_TEMPLATE.md, archive/2021-03-22-DssSpell.sol, archive/2021-03-22-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
https://app.clubhouse.io/scdomaincommunityteam/story/10280/monday-22nd-mips-executive
=> MIPs executive March 22nd, 2021 (SC-10280)

LICENSE, archive/2021-03-26-DssSpell.sol, archive/2021-03-26-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
=> SC-10406 2021-03-26 Executive

archive/2021-04-02-DssSpell.sol, archive/2021-04-02-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
https://app.clubhouse.io/scdomaincommunityteam/story/10644/friday-2nd-april-executive
=> SC-10644 2021-04-02 Executive

archive/2021-04-26-DssSpell.sol, archive/2021-04-26-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
=> MIPs Executive April 26th, 2021 (SC-11459)

archive/2021-05-24-DssSpell.sol, archive/2021-05-24-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
=> PE-544 2021-05-24 Monthly Executive Spell

archive/2021-06-18-DssSpell.sol, archive/2021-06-18-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol, src/test/addresses_mainnet.sol
=> PE-569: 2021-06-18 Executive Spell

archive/2021-07-17-DssSpell.sol, archive/2021-07-17-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
=> PE-617: 2021-07-17 replacement spell

.github/PULL_REQUEST_TEMPLATE.md
Addresses faulty spell postmortem action item: https://github.com/makerdao/smart-contracts-team-pm/issues/630
=> Add PR checklist item to notify external teams

.github/PULL_REQUEST_TEMPLATE.md, src/DssSpell.t.sol
Addresses https://github.com/makerdao/smart-contracts-team-pm/issues/627 for `mainnet`. Will backport to `spells-kovan`.
=> Rwa dc tests

src/DssSpell.sol, src/DssSpell.t.sol
- Removes  the old deployer 7 address from the `RWA001` output conduit.
- Adds the Genesis broker/dealer address to the `RWA001` output conduit.
- Increases the debt ceiling from 1000 DAI to 15 million DAI.
```haskell
Running 16 tests for src/DssSpell.t.sol:DssSpellTest
[PASS] testRWAUpdates() (gas: 587408)
[PASS] testFail_notScheduled() (gas: 4759)
[PASS] test_auth_in_sources() (gas: 281473904105414)
[PASS] test_use_eta() (gas: 171273)
[PASS] testOnTime() (gas: 329560)
[PASS] test_nextCastTime() (gas: 233759)
[PASS] testFailTooEarly() (gas: 204423)
[PASS] test_bytecode_matches() (gas: 1027146)
[PASS] test_auth() (gas: 281473906942261)
[PASS] testSpellIsCast_GENERAL() (gas: 6078352)
[PASS] testFailWrongDay() (gas: 204399)
[PASS] testCastCost() (gas: 331152)
[PASS] testNewChainlogValues() …
```
=> PE-637-6s: RWA DC Broker/Dealer Updates

src/DssSpell.sol
=> Add L2 test spells

README.md, archive/2021-09-24-DssSpell.sol, archive/2021-09-24-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
=> PE-678: MakerDAO September 24, 2021 Executive Spell

archive/2021-10-29-DssSpell.sol, archive/2021-10-29-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol, src/test/addresses_mainnet.sol
=> October 29th Executive

archive/2021-11-05-DssSpell.sol, archive/2021-11-05-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
=> PE-728 2021-11-05 Executive

src/DssSpell.t.base.sol
Replaces the hard coded list of collateral that are being offboarded with an attribute in the collateral definitions.
=> add a collateral offboarding flag

src/DssSpell.sol, src/DssSpell.t.sol
=> Feb 3 fix vest streams

archive-dssspell.sh
- Porting https://github.com/makerdao/spells-goerli/pull/54
- Cleanup (Remove L7) https://github.com/makerdao/spells-goerli/pull/47#discussion_r801673534
=> Optimize `archive-dssspell.sh`

Makefile, scripts/test-dssspell-forge.sh, scripts/test-dssspell.sh
- Porting https://github.com/makerdao/spells-goerli/pull/60
- Includes extra shellcheck fix for `test-dssspell.sh` on L4
=> Add rpc block number option in `test-dssspell.sh`

Makefile, scripts/diff-archive-dssspell.sh
- Porting https://github.com/makerdao/spells-goerli/pull/53
- Tested against latest archived spell:
`make diff-archive-spell date=2022-03-11`
=> `diff-archive-dssspell.sh`

src/DssSpell.t.base.sol, src/DssSpell.t.sol
- Use `GemAbstract` in Collateral Integration Tests
- Cleanup
=> Use `GemAbstract` in collateral integration tests

src/DssSpell.t.sol
Short circuit test if chainlog version is updated
=> Fix chainlog test

src/test/config-starknet.sol
A few extract Starknet DAI bridge related checks.
=> Extra checks

.github/workflows/tests.yaml, Makefile, README.md, scripts/get-created-timestamp.sh, scripts/test-dssspell.sh, src/DssSpell.sol, src/DssSpell.t.base.sol, src/DssSpell.t.sol, src/DssSpellCollateral.sol, src/test/addresses_deployers.sol, src/test/addresses_mainnet.sol, src/test/addresses_wallets.sol, src/test/config.sol, src/test/rates.sol, src/test/starknet.t.sol
- Porting:
- https://github.com/makerdao/spells-goerli/pull/80
- https://github.com/makerdao/spells-goerli/pull/89
- Minor Changes and Cleanups
=> Housekeeping

src/DssSpell.sol, src/DssSpellCollateral.sol, src/test/config.sol
=> Enable autoline for RWA007-A

scripts/deploy.sh
- Porting https://github.com/makerdao/spells-goerli/pull/118
=> Add `ETHERSCAN_API_KEY` check  in `deploy.sh`

Makefile, scripts/hash-exec-copy.sh
- Porting https://github.com/makerdao/spells-goerli/pull/117
=> `hash-exec-copy.sh`

src/DssSpell.sol, src/DssSpell.t.base.sol, src/DssSpell.t.sol, src/test/addresses_deployers.sol, src/test/addresses_mainnet.sol, src/test/config.sol
=> GNO-A Onboarding & RENBTC-A Offboarding

src/test/addresses_deployers.sol
=> Add new PE deployer

.gitmodules, src/DssSpell.t.base.sol, src/DssSpell.t.sol, src/test/config.sol
porting these changes to mainnet: https://github.com/makerdao/spells-goerli/pull/150
=> Add dss test

foundry.toml, scripts/test-dssspell-forge.sh, src/DssSpell.t.sol
add L2 tests for spell.
Need to
=> PE-1184 l2 tests

scripts/deploy.sh
- Porting https://github.com/makerdao/spells-goerli/pull/171
=> Improve `deploy.sh`

scripts/wards.sh
Remove brackets from cast call return
=> Fix for wards script

src/DssSpell.sol, src/DssSpell.t.sol
Currently failing. Need to update oracle adapter.
=> Add oracle check precision

Makefile, README.md, scripts/cast-on-tenderly/.gitignore, scripts/cast-on-tenderly/index.js, scripts/cast-on-tenderly/package-lock.json, scripts/cast-on-tenderly/package.json
Transfer of code from https://github.com/makerdao/spells-goerli/pull/225 improvement
https://dashboard.tenderly.co/shared/fork/simulation/5d4f655a-2fb3-4780-9015-f3e6f7e32a7f
tested for spell [0xD97B4e0b43708c836935c9b2320f57074DC1D146](https://etherscan.io/address/0xD97B4e0b43708c836935c9b2320f57074DC1D146) with the following diff on commit `548ad26c2bc47fba893e39cbe27153a9bce4c9ea`:
```
git diff
diff --git a/scripts/cast-on-tenderly/index.js b/scripts/cast-on-tenderly/index.js
index 3152253..991acf8 100644
--- a/scripts/cast-on-tenderly/index.js
+++ b/scripts/cast-on-tenderly/index.js
@@ -23,7 +23,7 @@ const makeTenderlyApiRequest = async function (path) {
const API_BASE = `https://api.tenderly.co/api/v1/account/${process.env.TENDERLY_USER}/project/${process.env.TENDERLY_PROJECT}`; …
```
=> Add cast on tenderly script

Makefile, remappings.txt
Mainnet version of the https://github.com/makerdao/spells-goerli/pull/250 PR that fixes broken compilation via dapp tools
=> Add remappings
