archive/2020-10-16-DssSpell.sol, archive/2020-10-16-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
https://app.clubhouse.io/maker/story/6609/add-eth-b-collateral-mainnet
* Adds ETH-B collateral with parameters defined in the [polling proposal](https://vote.makerdao.com/polling-proposal/qmzvcsx9lkpejp8xpxsvkvvfot8anarmdq17afjdbbu3wu)
* Adds some tests to ensure deployer05 has been denied and pauseproxy has been relied.
* NOTE: I've left the unused functions in the collateral onboarding script in here but commented out. On the one hand, I think it's important to keep our onboarding heuristic in tact so that people can see that the decisions were deliberate, but on the other hand we may not want to display the commented out code. I'm not particularly committed to keeping the commented code in there, but if we do remove it we should put a comment with a link to the script template so that …
=> SC-6609: 20201016 Exec - ETH-B Collateral Onboarding

archive/2020-10-23-DssSpell.sol, archive/2020-10-23-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
https://app.clubhouse.io/maker/story/6623/2020-10-23-executive
Governance copy:
https://github.com/makerdao/community/blob/master/governance/votes/Executive%20vote%20-%20October%2023%2C%202020.md
Increases the surplus buffer to 4 million DAI and whitelists B Protocol to read from the ETHUSD `Median` and `Osm`.
=> SC-6623: 2020-10-03 Executive

compare-bytecode.sh
Adds an output to the bytecode checker to verify that compared variables are not null.
```
bmcmichael@bmcx1c:~/makerdao/dss-launch$ ./compare-bytecode.sh 
Compiled Bytecode: 0x608060405234801561001057600080fd5b5060...
On-Chain Bytecode: 0x608060405234801561001057600080fd5b5060...
SUCCESS! Bytecodes match.
```
If variables are null they will match, this just echoes a portion of the variables that are being compared as a sanity check.
=> Show bytecode snippet

compare-bytecode.sh, src/DssSpell.t.sol
Change address to optional param in bytecode script, if not provided, pulls from test file.
```
➜  spells-mainnet git:(add-deployed-address-check) ./compare-bytecode.sh 0xBc59B45F54f88EfD5f8f5cf0FbcBf5970A9255cc
SUCCESS! Bytecodes match.
➜  spells-mainnet git:(add-deployed-address-check) ✗ ./compare-bytecode.sh 0xdA0Ab1e0017DEbCd72Be8599041a2aa3bA7e740F
FAILURE. Bytecodes do NOT match.
➜  spells-mainnet git:(add-deployed-address-check) ✗ ./compare-bytecode.sh
SUCCESS! Bytecodes match.
```
=> feat: Change address to optional param in compare-bytecode.sh

archive/2020-10-30-DssSpell.sol, archive/2020-10-30-DssSpell.t.sol, src/DssSpell.sol, src/DssSpell.t.sol
- Increases the GSM delay from `12 hours` to `72 hours`
- Removes authority from `OsmMom`
- Removes authority from `FlipperMom`
=> SC-6974: 2020-10-30 Executive Spell

src/DssSpell.sol
Adds a public `officeHours` bool and updates the modifier to operate if it's true.
A public `officeHours` bool was requested by the frontend team as a way to detect whether a spell will be subject to the office hours modifier. This has been added to the dss-exec-lib version of DssExec (https://github.com/makerdao/dss-exec-lib/blob/master/src/DssExec.sol#L41) and I'm backporting here so that they can start working on their UI for it.
=> SC-7271-20201120-weekly-exec

src/DssSpell.sol, src/DssSpell.t.sol
The relevant test will fail until DssExecLib.sol is deployed with the changes introduced in https://github.com/makerdao/dss-exec-lib/pull/38
=> add tests for flap

test-dssspell.sh
`seth chain` appears to always source from sethrc if it exports `ETH_RPC_URL` so we should use the `--rpc-url` [flag](https://github.com/dapphub/dapptools/tree/master/src/seth#connecting-to-the-blockchain) for `seth chain` This prevents hidden defaults. 
Test case to show the issue:
1. define `ETH_RPC_URL` in your `.sethrpc` file.
2. in your terminal `export ETH_RPC_URL=a`  
3. run `make test`
4. You should not get past the check for `ETH_RPC_URL && $(seth chain) == "ethlive"` but on the main branch you would and the tests will fail because `a` is not a valid URL.
My concern is that if we export an ETH_RPC_URL but also have one set in `sethrc` then `seth chain` would us the `sethrc` one.  This change forces it to use the exported one which is the same thing we are doing for `dapp` when we …
=> Source dapprc

src/DssSpell.t.base.sol, src/DssSpell.t.sol
So that we can use `GemAbstract` for gems and `DSTokenAbstract` for `gov`, we need to generalize the input for `giveTokens`
=> generalize give tokens for Gems and Gov

scripts/verify.py
- Porting https://github.com/makerdao/spells-goerli/pull/63
=> Remove `verify.py` temporary license workaround

scripts/get-arb-relay-cost.sh, scripts/get-opt-relay-cost.sh, src/DssSpell.sol, src/DssSpell.t.sol, src/test/starknet.t.sol
=> [PE 1184] add Opt & Arb relay calls

scripts/get-arb-relay-cost.sh, scripts/get-opt-relay-cost.sh, src/DssSpell.sol, src/DssSpell.t.sol, src/test/starknet.t.sol
=> Pe 1184 : add relay to L2 

scripts/hash-exec-copy.sh
This script currently does not work for anyone whose system is configured to a language that is not English, because `date %B` returns the [locale's full month name](https://man7.org/linux/man-pages/man1/date.1.html).
=> Fix `make exec-hash` for non-English systems

.github/workflows/tests.yaml, Makefile, scripts/test-dssspell-forge.sh
This is a port from [spells-goerli#220](https://github.com/makerdao/spells-goerli/pull/220). See the original PR for details.
=> Feature: add `no-match` option to `make test-forge` / Refactor: use `make test` instead of `make test-forge` in CI

scripts/cast-on-tenderly/index.js
Closes https://github.com/makerdao/spells-mainnet/issues/407
This PR fixes the problem with the `cast-on-tenderly` script reported in https://github.com/makerdao/spells-mainnet/issues/407. 
After creating Tenderly testnets, the endpoint returns an array of RPC endpoints within `container.connectivityConfig.endpoints` with two currently items: one which accepts cheat codes and one that doesn't. In order to get desired one, we initially used their internal `endpoints[].displayName` properly (as far as I remember, there were no dedicated properly to specify which one is which), but now they introduced `endpoints[].private` boolean which is also mentioned in the [API docs](https://tenderlydev.notion.site/API-Endpoints-d6c444c0f6934727a2297b958da19a4b#:~:text=endpoint%20that%20has-,private%20se …
=> Fix `cast-on-tenderly` script

scripts/check-deployed-dssspell.sh
=> [MAINTENANCE] Fix: `check-deployed-spell` script

src/DssSpell.t.base.sol, src/DssSpell.t.sol
Currently we get the following compiler warnings when running the spell tests:
```
./scripts/test-dssspell-forge.sh no-match="" match="testDaoResolutions" block=""
Using DssExecLib at: 0x8De6DDbCd5053d32292AAA0D2105A32d108484a6
[⠊] Compiling...
[⠃] Compiling 3 files with Solc 0.8.16
[⠊] Solc 0.8.16 finished in 2.77s
Compiler run successful with warnings:
Warning (2018): Function state mutability can be restricted to view
--> src/DssSpell.t.base.sol:983:5:
|
983 |     function _getOSMPrice(address pip) internal returns (uint256) {
|     ^ (Relevant source part starts here and spans across multiple lines).
Warning (2018): Function state mutability can be restricted to view
--> src/DssSpell.t.base.sol:999:5:
|
999 |     function _getUNIV2LPPrice(address pip) internal returns (uint256) {
| …
```
=> Chore: fix compiler warnings

scripts/cast-on-tenderly/index.js
This PR closes #452. 
As outlined in the issue, there was some changes introduced in tenderly API which made our script failed on last stage (`publishTenderlyTestnet`). 
The suggested change in issue was confirmed during last spell deployment and included in the current PR.
=> fix: cast-on-tenderly script

scripts/cast-on-tenderly/index.js
Currently, `make cast-on-tenderly ...` is failing with the following error:
```js
makeTenderlyApiRequest error {
status: 400,
statusText: 'Bad Request',
headers: Object [AxiosHeaders] {
'content-type': 'application/json; charset=utf-8',
'user-agent': 'axios/1.6.5',
vary: 'Origin,Origin',
'x-tdly-limit': '400',
'x-tdly-remaining': '399',
'x-tdly-reset-timestamp': '1744034055077',
date: 'Mon, 07 Apr 2025 13:53:15 GMT',
'content-length': '121',
'x-envoy-upstream-service-time': '625',
'x-ratelimit-limit': '600, 600;w=60',
'x-ratelimit-remaining': '599',
'x-ratelimit-reset': '46',
server: 'envoy',
via: '1.1 google',
'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'
},
config: {
transitional: {
silentJSONParsing: true,
forcedJSONParsing: true,
clarifyTimeoutError: false
},
adapter: [ …
```
=> Fix: `cast-on-tenderly` BAD_REQUEST error

.github/workflows/tests.yaml
The current `test.yml` GitHub action was created back when there was no stable release for Foundry.
It explicitly uses the `nightly` tag when installing Foundry.
Against all odds, we didn't have major issues so far, however a recent nightly build most likely introduced a bug, reported [here](https://github.com/foundry-rs/foundry/issues/10574).
This PR fixes the issue by removing the `nightly` tag, leaving the default value (`stable`).
=> Use stable Foundry release in CI
